apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
 name: pwx-backuplocation
 namespace: kube-system
 annotations:
   stork.libopenstorage.org/skipresource: "true"
location:
 type: s3
 # path is where backup bits, such as metadata, will be saved (i.e. "stork" folder will get created under s3 bucket)
 path: "stork"
 sync: true
 s3Config:
   region: "us-east-1"
   accessKeyID: "<redacted>"
   secretAccessKey: "<redacted>"
   # endpoint reference: https://docs.aws.amazon.com/general/latest/gr/rande.html
   # endpoint may differ per region
   endpoint: "<endpoint>"
   disableSSL: true
