apiVersion: autopilot.libopenstorage.org/v1alpha1
kind: AutopilotRule
metadata:
  name: volume-resize-kafka
spec:
  actions:
  - name: openstorage.io.action.volume/resize
    params:
      scalepercentage: "100"
  conditions:
    expressions:
    - key: 100 * (px_volume_usage_bytes / px_volume_capacity_bytes)
      operator: Gt
      values:
      - "50"
    provider: prometheus
    type: metrics
  namespaceSelector: {}
  pollInterval: 10
  selector:
    matchLabels:
      app: cp-kafka